### ISSUE TITLE
Wow script with good setup

### ISSUE THREAD

**Issue by docop** [Scotchman0/XRDP-for-ubuntu#1]
Hi So i end up seing your script. And seriously, i always deploy line by line, but with yours, i see it quite clearly and the comment are good to get how this thing work.
I will try to do my own script for Centos. As i mainly do min inst, with xfce and other install.

Thanks

**Comment by Scotchman0** [comment]
Thanks Docop! I appreciate the feedback - hopefully it's helping make some lives' easier! I'll look forward to seeing your version for CentOS :) Stay safe out there!
